/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteAccountRouteImport } from './routes/_site.account'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteShopRouteImport } from './routes/_site.shop'
import { Route as SiteTrackOrderRouteImport } from './routes/_site.track-order'
import { Route as SiteWishlistRouteImport } from './routes/_site.wishlist'
import { Route as SiteProductSlugRouteImport } from './routes/_site.product.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrackOrderRoute = SiteTrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWishlistRoute = SiteWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductSlugRoute = SiteProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/shop': typeof SiteShopRoute
  '/track-order': typeof SiteTrackOrderRoute
  '/wishlist': typeof SiteWishlistRoute
  '/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/shop': typeof SiteShopRoute
  '/track-order': typeof SiteTrackOrderRoute
  '/wishlist': typeof SiteWishlistRoute
  '/': typeof SiteIndexRoute
  '/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/account': typeof SiteAccountRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/track-order': typeof SiteTrackOrderRoute
  '/_site/wishlist': typeof SiteWishlistRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/track-order'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/track-order'
    | '/wishlist'
    | '/'
    | '/product/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/account'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/shop'
    | '/_site/track-order'
    | '/_site/wishlist'
    | '/_site/'
    | '/_site/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account': {
      id: '/_site/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/track-order': {
      id: '/_site/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof SiteTrackOrderRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/wishlist': {
      id: '/_site/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof SiteWishlistRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/product/$slug': {
      id: '/_site/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof SiteProductSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAccountRoute: typeof SiteAccountRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteTrackOrderRoute: typeof SiteTrackOrderRoute
  SiteWishlistRoute: typeof SiteWishlistRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductSlugRoute: typeof SiteProductSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAccountRoute: SiteAccountRoute,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteShopRoute: SiteShopRoute,
  SiteTrackOrderRoute: SiteTrackOrderRoute,
  SiteWishlistRoute: SiteWishlistRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductSlugRoute: SiteProductSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
